config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transfers
  resources :transactions
  resources :payments
  resources :payees
  resources :accounts
  resources :users

  root to: 'accounts#index'

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :from_account
  belongs_to :to_account
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers
  # GET /transfers.json

  def index
		@user = current_user
    @transfers = Transfer.all
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
		@user = current_user
  end

  # GET /transfers/new
  def new
		@user = current_user
    @transfer = Transfer.new
  end

  # GET /transfers/1/edit
  def edit
		@user = current_user
  end

  # POST /transfers
  # POST /transfers.json
  def create
		@user = current_user
    @transfer = Transfer.new(transfer_params)

    respond_to do |format|
      if @transfer.save
        format.html { redirect_to @transfer, notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to @transfer, notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to transfers_url, notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:from_account_id, :to_account_id, :amount, :effective_ts)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_account_id %><br>
    <%= f.text_field :from_account_id %>
  </div>
  <div class="field">
    <%= f.label :to_account_id %><br>
    <%= f.text_field :to_account_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :effective_ts %><br>
    <%= f.datetime_select :effective_ts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<h1>Editing Transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @transfer %> |
<%= link_to 'Back', transfers_path %>

app/views/transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transfers</h1>

<table>
  <thead>
    <tr>
      <th>From account</th>
      <th>To account</th>
      <th>Amount</th>
      <th>Effective ts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transfers.each do |transfer| %>
      <tr>
        <td><%= transfer.from_account %></td>
        <td><%= transfer.to_account %></td>
        <td><%= transfer.amount %></td>
        <td><%= transfer.effective_ts %></td>
        <td><%= link_to 'Show', transfer %></td>
        <td><%= link_to 'Edit', edit_transfer_path(transfer) %></td>
        <td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transfer', new_transfer_path %>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', transfers_path %>

app/views/transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From account:</strong>
  <%= @transfer.from_account %>
</p>

<p>
  <strong>To account:</strong>
  <%= @transfer.to_account %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transfer.amount %>
</p>

<p>
  <strong>Effective ts:</strong>
  <%= @transfer.effective_ts %>
</p>

<%= link_to 'Edit', edit_transfer_path(@transfer) %> |
<%= link_to 'Back', transfers_path %>