config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :transfers
  resources :transactions
  resources :payments
  resources :payees
  resources :accounts
  resources :users

  root to: 'accounts#index'

end

app/models/payee.rb
class Payee < ActiveRecord::Base
  belongs_to :uers
end

app/controllers/payees_controller.rb
class PayeesController < ApplicationController
	before_action :authenticate_user!
  before_action :set_payee, only: [:show, :edit, :update, :destroy]
	before_action :set_section

  # GET /payees
  # GET /payees.json
  def index
		@user = current_user
    @payees = @user.payees
  end

  # GET /payees/1
  # GET /payees/1.json
  def show
		@user = current_user
  end

  # GET /payees/new
  def new
		@user = current_user
    @payee = Payee.new
  end

  # GET /payees/1/edit
  def edit
		@user = current_user
  end

  # POST /payees
  # POST /payees.json
  def create
    @payee = Payee.new(payee_params)
		@payee.user_id = current_user.id

    respond_to do |format|
      if @payee.save
        format.html { redirect_to @payee, notice: 'Payee was successfully created.' }
        format.json { render :show, status: :created, location: @payee }
      else
        format.html { render :new }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payees/1
  # PATCH/PUT /payees/1.json
  def update
    respond_to do |format|
      if @payee.update(payee_params)
        format.html { redirect_to @payee, notice: 'Payee was successfully updated.' }
        format.json { render :show, status: :ok, location: @payee }
      else
        format.html { render :edit }
        format.json { render json: @payee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payees/1
  # DELETE /payees/1.json
  def destroy
    @payee.destroy
    respond_to do |format|
      format.html { redirect_to payees_url, notice: 'Payee was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payee
      @payee = Payee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payee_params
      params.require(:payee).permit(:name, :description, :address, :uers_id)
    end

		def set_section
			@section = 'payments'
		end
end

app/helpers/payees_helper.rb
module PayeesHelper
end

app/views/payees/_form.html.erb
<div class="row">	
	<div class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
		<%= form_for(@payee, :html => {:role => 'form'}) do |f| %>
			<% if @payee.errors.any? %>
				<div id="error_explanation" class="alert alert-danger">
					<button class="close" data-dismiss="alert">×</button>
					<h2><%= pluralize(@payee.errors.count, "error") %> prohibited this payee from being saved:</h2>
					<ul>
					<% @payee.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
					</ul>
				</div>
			<% end %>

			<div class="form-group">
				<%= f.label :name %><br>
				<%= f.text_field :name, :class => "form-control", autofocus: true, required: true %>
			</div>
			<div class="form-group">
				<%= f.label :description %><br>
				<%= f.text_field :description, :class => "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :address %><br>
				<%= f.text_field :address, :class => "form-control"  %>
			</div>
		
			<div class="form-group"> 
				<%= link_to 'Back', payees_path, :class => "btn btn-default", :role => "button" %>
				<%= f.submit "Save", :class => "btn btn-primary", :role => "button" %>
			</div>
		<% end %>
	</div>
</div>

app/views/payees/edit.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1"> 
		<h2> <%= t(:edit_payee) %> </h2> 
	</div>
</div>

<%= render 'form' %>

app/views/payees/index.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
		<h2> <%= t(:manage_payees) %> </h2>
	</div>
</div>
<div class="row">
	<div class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
		<div class="row">
			<div class="col-xs-12">
	      <table class="table table-hover ">
          <thead>                         
            <tr>                                                                 
		          <th> <%= t(:name) %> </th> 
							<th> <%= t(:description) %> </th>                                      
		          <th> </th>
	          </tr>                                                                  
  	      </thead>
      	  <tbody>
						<% @payees.each do |payee| %>                             
        	  	<tr>
          	  	<td> <%= payee.name %> </td>
								<td> <%= payee.description %> </td>       
            		<td> <%= link_to t(:details), payee %> </td>              
          		</tr>
						<% end %>
					</tbody>
				</table>                                                                   
			</div>
		</div>  
	</div>
</div>

<div class="row">
	<div class="col-sm-1 col-sm-offset-2 col-xs-10 col-xs-offset-1">
		<%= link_to t(:new_payee), new_payee_path, :class => "btn btn-primary", :role => "button" %>
	</div>
</div>                                                                                  

app/views/payees/new.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1"> 
		<h2> <%= t(:new_payee) %> </h2> 
	</div>
</div>

<%= render 'form' %>

app/views/payees/show.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
		<h2> <%= @payee.name %>  </h2>
	</div>
</div>
<div class="row">
	<div class="col-sm-offset-3 col-sm-6 col-xs-offset-1 col-xs-10">
		<div class="row">
			<div class="col-xs-12">
				<h2> <small> <%= t(:description) %> </small> </h2>
				<p> <%= @payee.description %> </p>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<h2> <small> <%= t(:address) %> </small> </h2>
			</div>
			<div class="col-xs-12">
				<p> <%= @payee.address %> </p>
			</div>
		</div>
	</div>
</div>
<div class="row" style="margin-top:20px;">
	<div class="col-sm-8 col-sm-offset-2 col-xs-offset-1 col-xs-10">
		<%= link_to t(:back), payees_path, :class => "btn btn-default", :role => "button" %>
		<%= link_to t(:edit), edit_payee_path(@payee), :class => "btn btn-primary", :role => "button" %> 
		<%= link_to t(:delete), @payee, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :role => "button" %>
	</div>
</div>